# Generated by Django 5.1.7 on 2025-03-28 08:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Минимальная длина - 2 символа.')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'operation categories',
                'db_table': 'cfm_operation_category',
            },
        ),
        migrations.CreateModel(
            name='OperationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Минимальная длина - 2 символа.')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'operation statuses',
                'db_table': 'cfm_operation_status',
            },
        ),
        migrations.CreateModel(
            name='OperationSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Минимальная длина - 2 символа.')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfm.operationcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'operation subcategories',
                'db_table': 'cfm_operation_subcategory',
            },
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Минимальная длина - 2 символа.')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cfm_operation_type',
            },
        ),
        migrations.AddField(
            model_name='operationcategory',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfm.operationtype'),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfm.operationcategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfm.operationstatus')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfm.operationsubcategory')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfm.operationtype')),
            ],
            options={
                'ordering': ['-created_at', 'total'],
            },
        ),
        migrations.AddConstraint(
            model_name='operationstatus',
            constraint=models.UniqueConstraint(fields=('user', 'status_name'), name='unique_status_name_per_user', violation_error_message='Такой статус уже существует!'),
        ),
        migrations.AddConstraint(
            model_name='operationsubcategory',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'subcategory_name'), name='unique_category_and_subcategory_per_user', violation_error_message='Такая связка уже существует!'),
        ),
        migrations.AddConstraint(
            model_name='operationtype',
            constraint=models.UniqueConstraint(fields=('user', 'type_name'), name='unique_type_name_per_user', violation_error_message='Такой тип уже существует!'),
        ),
        migrations.AddConstraint(
            model_name='operationcategory',
            constraint=models.UniqueConstraint(fields=('user', 'type', 'category_name'), name='unique_type_and_category_per_user', violation_error_message='Такая связка уже существует!'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(condition=models.Q(('total__gt', 0)), name='total_gt_0'),
        ),
    ]
